# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Build to Crashlytics Alpha Channel"
  lane :alpha do
    android_set_version_name(
      version_name: ENV["VERSION_NAME"],
      gradle_file: "app/build.gradle"
    )

    increment_version_code(
        gradle_file_path: "app/build.gradle"
    )
    
    gradle(task: "clean")

    gradle(
        task: "assemble",
        build_type: "Release",
        print_command: false,
        properties: {
          "android.injected.signing.store.file" => "keystore.jks",
          "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
          "android.injected.signing.key.alias" => ENV["KEYSTORE_ALIAS"],
          "android.injected.signing.key.password" => ENV["KEYSTORE_ALIAS_PASSWORD"],
        }
    )
    
    supply(
        track: "alpha",
        apk: "app/build/outputs/apk/release/app-release.apk"
    )
  end

  desc "Just build the APK"
  lane :apk do
    android_set_version_name(
      version_name: ENV["GIT_COMMIT"],
      gradle_file: "app/build.gradle"
    )

    increment_version_code(
        gradle_file_path: "app/build.gradle"
    )
    
    gradle(task: "clean")

    gradle(
        task: "assembleDebug",
        build_type: "Debug",
        properties: {
          "android.injected.signing.store.file" => "keystore.jks",
          "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
          "android.injected.signing.key.alias" => ENV["KEYSTORE_ALIAS"],
          "android.injected.signing.key.password" => ENV["KEYSTORE_ALIAS_PASSWORD"],
        }
    )
  end
end
